# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22-alpine

# Create app directory
WORKDIR /app

# Copy package files and tsconfig
COPY package*.json ./
COPY tsconfig.json ./

# Install dependencies (including dev dependencies) without running scripts
RUN npm ci --ignore-scripts

# Copy source code after installing dependencies so dependency layers stay cached
COPY src ./src

# Build the project
RUN npm run build

# Optionally expose a port; MCP usually uses stdio, but exposing a port for health checks if needed
EXPOSE 3000

# Start the MCP server
CMD [ "npm", "run", "start:sse" ]
